/**
 * netspec.mjs — 受控阻抗規格表（板廠真正會讀的那一張）
 *
 * 為什麼要有這個檔：阻抗目標與差分對關係一直只活在編輯器與 DRC 裡。
 * 板廠收到的是 Gerber ＋ 鑽孔 ＋ 網表，網表只有 net 名——**使用者要求的阻抗
 * 根本沒有傳出去**。板廠不會通靈，沒有這張表就是照預設疊構做，做完才發現不對。
 *
 * 這張表寫什麼、不寫什麼（重要）：
 *   - 寫**設計端指定的目標**（Z0 / Zdiff / 容差 / 配對 net）。
 *   - 寫**實際畫出來的幾何**（每個 net 用到的層與線寬，直接量走線）。
 *   - **不重算阻抗**。IPC-2141 的公式在 `pcb-nets.js`（瀏覽器端）只有一份；
 *     在這裡再寫一份，兩份遲早分岔，而分岔的症狀是「畫面說 50Ω、送廠的檔說 47Ω」。
 *     所以這裡明講「計算值見編輯器」，不給第二個數字。
 *
 * 沒有任何 net 設過屬性時回 null——空表比沒有表更糟，板廠會以為這片板沒有阻抗要求。
 */

const r3 = v => Math.round(v * 1000) / 1000;
const S = v => String(v == null ? '' : v).trim();

/** 每個 net 實際畫出來的層與線寬（去重）。量的是真的走線，不是規則裡寫的。 */
function geometryOf(state, net) {
  const segs = (state.traces || []).filter(t => S(t.net) === net && (t.x1 !== t.x2 || t.y1 !== t.y2));
  const layers = [], widths = [];
  for (const t of segs) {
    const l = S(t.layer) || 'F.Cu';
    if (layers.indexOf(l) < 0) layers.push(l);
    const w = r3(t.width || 0.3);
    if (widths.indexOf(w) < 0) widths.push(w);
  }
  return { layers, widths: widths.sort((a, b) => a - b), segs: segs.length };
}

/**
 * 回 { text, rows } 或 null（沒有任何 net 設過屬性）。
 * rows 給測試與呼叫端用，text 是要放進打包的檔案內容。
 */
function buildNetSpec(state, opts) {
  const o = opts || {};
  const props = (state && state.netProps) || {};
  const names = Object.keys(props).filter(n => {
    const p = props[n] || {};
    return (Number(p.z0) > 0) || (Number(p.zdiff) > 0) || S(p.pair) || S(p.note);
  }).sort();
  if (!names.length) return null;

  const rows = names.map(net => {
    const p = props[net] || {};
    const g = geometryOf(state, net);
    return {
      net,
      z0: Number(p.z0) > 0 ? Number(p.z0) : null,
      zdiff: Number(p.zdiff) > 0 ? Number(p.zdiff) : null,
      tol: Number(p.ztol) > 0 ? Number(p.ztol) : 10,
      pair: S(p.pair) || '',
      note: S(p.note),
      layers: g.layers,
      widths: g.widths,
      routed: g.segs > 0
    };
  });

  const pad = (s, n) => String(s).padEnd(n);
  const L = [];
  L.push('Controlled impedance requirements for ' + (o.name || 'board'));
  L.push('Generated by HardwareAI. Targets are the designer\'s requirement;');
  L.push('widths/layers below are measured from the actual traces in this design.');
  L.push('Computed impedance is shown in the editor (IPC-2141) and is deliberately');
  L.push('not repeated here, so there is only one number to trust.');
  L.push('');
  L.push([pad('Net', 18), pad('Z0(ohm)', 9), pad('Zdiff', 8), pad('Tol%', 6),
          pad('Pair', 16), pad('Layers', 18), pad('Width(mm)', 14), 'Note'].join(''));
  L.push('-'.repeat(110));
  for (const r of rows) {
    L.push([
      pad(r.net, 18),
      pad(r.z0 == null ? '-' : r.z0, 9),
      pad(r.zdiff == null ? '-' : r.zdiff, 8),
      pad(r.tol, 6),
      pad(r.pair || '-', 16),
      // 沒繞的 net 明講，不要留一格空白讓人以為是漏印
      pad(r.routed ? r.layers.join('/') : 'NOT ROUTED', 18),
      pad(r.routed ? r.widths.join('/') : '-', 14),
      r.note
    ].join(''));
  }
  L.push('');
  L.push('Notes:');
  L.push('- A net listed with more than one width or layer is routed that way in the');
  L.push('  design; that is information for the fab, not necessarily an error.');
  L.push('- "NOT ROUTED" means the requirement exists but no copper was drawn yet.');
  return { text: L.join('\n') + '\n', rows };
}

export { buildNetSpec, geometryOf as _geometryOf };
